import pg from 'pg';
import {config} from './config.js';
import {providers} from './providers/index.js';
import {createApp} from './app.js';
const c=config();
const db=new pg.Pool({connectionString:c.DATABASE_URL,max:5,connectionTimeoutMillis:10000,statement_timeout:10000});
await db.query('SELECT 1 FROM launch.users LIMIT 0');
const app=createApp({db,c,provider:providers(c)});app.locals.tracking.start();
const server=app.listen(c.PORT,'0.0.0.0',()=>console.log('Restricted staging API listening; bookings and payments disabled'));
process.on('SIGTERM',()=>server.close(()=>{app.locals.tracking.stop();db.end().then(()=>process.exit(0));}));
